apiVersion: apps/v1
kind: Deployment
metadata:
  name: tres-amigos-dc2
spec:
  selector:
    matchLabels:
      app: tres-amigos-dc2
  replicas: 1
  template:
    metadata:
      labels:
        app: tres-amigos-dc2
        env: localhost
    spec:
      containers:
      - name: tres-amigos-dc2
        image: docker.io/dsstevenmatison/tres-amigos:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
          - name: KEYSPACE
            value: "biometrics"
          - name: K8S_USERNAME
            valueFrom:
              secretKeyRef:
                name: k8ssandra-superuser 
                key: username
          - name: K8S_PASSWORD
            valueFrom: 
              secretKeyRef:
                name: k8ssandra-superuser 
                key: password               
          - name: K8S_AUTH_URL
            value: "http://k8ssandra-dc1-stargate-service:8081/v1/auth"
          - name: STARGATE_URL
            value: "http://k8ssandra-dc1-stargate-service:8082/v2/"
          - name: GRAPHQL_URL
            value: "http://k8ssandra-dc1-stargate-service:8080/graphql/"