apiVersion: "v1"
kind: "Service"
metadata:
  name: "tres-amigos-gcp-service"
  namespace: "default"
spec:
  ports:
  - protocol: "TCP"
    port: 80
  selector:
    app: "tres-amigos-gcp"
  type: "LoadBalancer"
  loadBalancerIP: ""
